name: flutter_ecommerce_app
description: A Flutter e-commerce app with cart, buy now, receipt, and scratch card

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  permission_handler: ^11.3.1
  pdf: ^3.10.7
  intl: ^0.18.1
  scratcher: ^2.2.0
  printing: ^5.12.0
  shared_preferences: ^2.2.2
  qr_flutter: ^4.1.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  flutter_lints: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpeg
    - assets/images/4.jpeg
    - assets/images/5.jpg
    - assets/images/6.jpeg
    - assets/images/7.jpeg
    - assets/images/8.jpeg
    - assets/images/9.jpg
    - assets/images/10.jpeg
    - assets/images/11.jpg
    - assets/images/12.jpg
    - assets/images/13.jpg
    - assets/images/14.jpg
    - assets/images/15.jpg
    - assets/images/16.jpeg
    - assets/images/17.jpg
    - assets/images/18.jpg
    - assets/images/19.jpg
    - assets/images/20.jpg
