// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgtCpK4OcbDoSRrj-kt8AEJuD-SI4XfRk',
    appId: '1:1033324897530:web:bd67c39f10dcc88f9dd543',
    messagingSenderId: '1033324897530',
    projectId: 'flutter-ecommerce-app-b2beb',
    authDomain: 'flutter-ecommerce-app-b2beb.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-app-b2beb.firebasestorage.app',
    measurementId: 'G-SR3K02PRBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpucK3y4Q6Ncx3ZA67YXq0wKm9Lt223qE',
    appId: '1:1033324897530:android:406919cbbc34b3859dd543',
    messagingSenderId: '1033324897530',
    projectId: 'flutter-ecommerce-app-b2beb',
    storageBucket: 'flutter-ecommerce-app-b2beb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe7F0kFElp-GGTWvk1Ln_xNlZPSmf2_RM',
    appId: '1:1033324897530:ios:68222350c5a7cff99dd543',
    messagingSenderId: '1033324897530',
    projectId: 'flutter-ecommerce-app-b2beb',
    storageBucket: 'flutter-ecommerce-app-b2beb.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe7F0kFElp-GGTWvk1Ln_xNlZPSmf2_RM',
    appId: '1:1033324897530:ios:68222350c5a7cff99dd543',
    messagingSenderId: '1033324897530',
    projectId: 'flutter-ecommerce-app-b2beb',
    storageBucket: 'flutter-ecommerce-app-b2beb.firebasestorage.app',
    iosBundleId: 'com.example.flutterEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgtCpK4OcbDoSRrj-kt8AEJuD-SI4XfRk',
    appId: '1:1033324897530:web:e24dffe2b7311ba79dd543',
    messagingSenderId: '1033324897530',
    projectId: 'flutter-ecommerce-app-b2beb',
    authDomain: 'flutter-ecommerce-app-b2beb.firebaseapp.com',
    storageBucket: 'flutter-ecommerce-app-b2beb.firebasestorage.app',
    measurementId: 'G-DGLX66GQ8V',
  );

}